# Generated by Django 5.0.6 on 2024-06-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=200)),
                ('senha', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Usuario',
            },
        ),
    ]
